services:
  web:
    build: ../rag-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ../rag-service
          target: /code
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: "cr.weaviate.io/semitechnologies/weaviate:1.28.5"
    ports:
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
  ollma:
    image: "ollama/ollama"
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama